<a href="https://colab.research.google.com/github/clobos/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [2]:
A = np.array([3,4,5])
A

array([3, 4, 5])

In [4]:
A.dtype

dtype('int64')

In [5]:
A.shape

(3,)

In [8]:
B = np.array([[2,3,4], [5,6,7]])
B


array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
B.dtype


dtype('int64')

In [11]:
B.shape

(2, 3)

In [12]:
B[0]

array([2, 3, 4])

In [14]:
B[:,1]

array([3, 6])

In [15]:
B[1,:]

array([5, 6, 7])

In [16]:
B*B

array([[ 4,  9, 16],
       [25, 36, 49]])

In [17]:
B + B

array([[ 4,  6,  8],
       [10, 12, 14]])

In [18]:
B - B

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [21]:
zeros2 = np.zeros((2,3))
zeros2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
unos = np.ones(3)
unos

array([1., 1., 1.])

In [23]:
unos2 = np.ones((2,3))
unos2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
unos3 = np.ones((2,3,4))
unos3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
np.dot(B, B.T)

array([[ 29,  56],
       [ 56, 110]])

In [25]:
np.dot(B,A)

array([38, 74])